const { Event } = require("../models");

const eventData = [
  {
        title: "Workout for 2020-11-17",
        isAllDay: false,
        start: "2020-11-17T11:30:00+09:00",
        end: "2020-11-17T12:00:00+09:00",
        goingDuration: 30,
        comingDuration: 30,
        color: "#ffffff",
        isVisible: true,
        bgColor: "#69BB2D",
        dragBgColor: "#69BB2D",
        borderColor: "#69BB2D",
        calendarId: "1",
        category: "allday",
        dueDateClass: "",
        customStyle: "cursor: default;",
        isPending: false,
        isFocused: false,
        isReadOnly: false,
        isPrivate: false,
        location: "",
        attendees: "",
        recurrenceRule: "",
        state: "",
      },
      {
        title: "completed with blocks",
        isAllDay: false,
        start: "2020-11-19T09:00:00+09:00",
        end: "2020-11-19T10:00:00+09:00",
        color: "#ffffff",
        isVisible: true,
        bgColor: "#54B8CC",
        dragBgColor: "#54B8CC",
        borderColor: "#54B8CC",
        calendarId: "1",
        category: "allday",
        dueDateClass: "",
        customStyle: "",
        isPending: false,
        isFocused: false,
        isReadOnly: false,
        isPrivate: false,
        location: "",
        attendees: "",
        recurrenceRule: "",
        state: "",
      },
      {
        title: "completed with blocks",
        isAllDay: false,
        start: "2020-11-16T09:00:00+09:00",
        end: "2020-11-16T10:00:00+09:00",
        color: "#ffffff",
        isVisible: true,
        bgColor: "#54B8CC",
        dragBgColor: "#54B8CC",
        borderColor: "#54B8CC",
        calendarId: "1",
        category: "allday",
        dueDateClass: "",
        customStyle: "",
        isPending: false,
        isFocused: false,
        isReadOnly: false,
        isPrivate: false,
        location: "",
        attendees: "",
        recurrenceRule: "",
        state: "",
      },
      {
        title: "Time Schedule Need BGCOLOR",
        isAllDay: false,
        start: "2020-11-17T09:00:00+09:00",
        end: "2020-11-17T10:00:00+09:00",
        color: "#ffffff",
        isVisible: true,
        bgColor: "#54B8CC",
        dragBgColor: "#54B8CC",
        borderColor: "#54B8CC",
        calendarId: "1",
        category: "time",
        dueDateClass: "",
        customStyle: "",
        isPending: false,
        isFocused: false,
        isReadOnly: false,
        isPrivate: false,
        location: "",
        attendees: "",
        recurrenceRule: "",
        state: "",
      },
];

const seedEvents = () => Event.bulkCreate(eventData);

module.exports = seedEvents;
